name: Build keycloak-scim and release

on:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - name: Set up JDK 17
        uses: actions/setup-java@99b8673ff64fbf99d8d325f52d9a5bdedb8483e9 # v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Gradle
        run: gradle shadowJar

      - uses: actions/upload-artifact@v4
        with:
          path: ./build/libs/*.jar
